name: build

on:
  push:
    branches:
      - 'master'
    tags:
      - '*.*.*'
  pull_request:
    branches:
      - 'master'

jobs:
  release:
    runs-on: windows-latest
    steps:
      -
        name: Prepare
        id: prepare
        run: |
          if [[ $GITHUB_REF == refs/tags/* ]]; then
            echo ::set-output name=version::${GITHUB_REF#refs/tags/}
          else
            echo ::set-output name=version::0.0.0
          fi
        shell: bash
      -
        name: Checkout
        uses: actions/checkout@v2.3.4
      -
        name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.13
      -
        name: Mage build
        uses: magefile/mage-action@v1
        with:
          version: latest
          args: build
      -
        name: UPX compress
        uses: crazy-max/ghaction-upx@v1
        if: success()
        with:
          version: latest
          file: bin/nodejs-portable.exe
          args: -fq
      -
        name: GitHub Release
        uses: softprops/action-gh-release@v1
        if: success() && startsWith(github.ref, 'refs/tags/')
        with:
          draft: true
          files: |
            bin/nodejs-portable.exe
          name: ${{ steps.prepare.outputs.version }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      -
        name: VirusTotal Scan
        uses: crazy-max/ghaction-virustotal@v2.2.1
        if: success() && startsWith(github.ref, 'refs/tags/')
        with:
          vt_api_key: ${{ secrets.VT_API_KEY }}
          files: |
            ./bin/nodejs-portable.exe
